config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get    'about',    to: 'static_pages#about'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :tweets, only: [:show,:new,:create] do
    resources :comments, only: [:create, :destroy ]
  end
  
  resources :relationships,       only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include SessionsHelper
  
  def home
    if logged_in?
      @tweets  = current_user.tweets.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
  
  def about
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class="center jumbotron">
  <h1>利用規約</h1>

  <h2>こちらは利用規約ページです</h2>
  
 <%= link_to "サインアップ", new_user_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>フィード</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>

<div class="center jumbotron">
  <h1>インスタクローン</h1>

  <h2>このページはサブ課題ようで作られたページです</h2>
  
 <%= link_to "サインアップ", new_user_path, class: "btn btn-lg btn-primary" %>
 <%= link_to "ログイン", login_path, class: "btn btn-lg btn-primary" %>
</div>

<% end %>