config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get    'about',    to: 'static_pages#about'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :tweets, only: [:show,:new,:create] do
    resources :comments, only: [:create, :destroy ]
  end
  
  resources :relationships,       only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <%= link_to "instaclone","#",class:"navbar-brand"%>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
               <%= link_to "Home",root_path,class:"nav-link" %>
              </li>
              <% if logged_in? %>
              <li class="nav-item">
                <%= link_to "Profile",current_user,class:"nav-link" %>
              </li>
              
              <li class="nav-item">
                <%= link_to "Users",users_path,class:"nav-link" %>
              </li>
              
              <li class="nav-item">
                <%= link_to "Log out", logout_path, method: :delete,class:"nav-link" %>
              </li>
              <% end %>
            </ul>
          </div>
        </nav>
 </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
     <%= render 'layouts/header' %>
     <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
  </body>
  
  <footer>
    <div class="container-fluid bg-light">
      <% if logged_in? %>
      <%= link_to "写真アップロード",new_tweet_path,class:"btn btn-primary" %>
      <% end %>
    </div>
  </footer>
  <%= debug(params) if Rails.env.development? %>
</html>